name: Upload assets on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: zip -r csbAdditional.zip module.json module

      - name: Upload module.json asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./module.json
          asset_name: module.json
          asset_content_type: application/json

      - name: Upload ZIP asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./csbAdditional.zip
          asset_name: csbAdditional.zip
          asset_content_type: application/zip
